### ISSUE TITLE
Pop up window is not scaleable

### ISSUE THREAD

**Issue by ba1020** [Zimbra-Community/pgp-zimlet#139]
when i want to encrypt the window that pops up is not scaleable while the boxes inside are !

**Comment by barrydegraaff** [comment]
Using Firefox?

**Comment by ba1020** [comment]
Iceweasel 38.2.1

**Comment by barrydegraaff** [comment]
Yeah, basically Firefox allows re-sizing of html input no matter what the specs/or developer intended. Also Debian changes the rendering/behavior of the browser. So iceweasel IS NOT firefox and since I switched to Fedora about 9 months back, I have NOT tested iceweasel, so there may be some bugs.

So for example in Google Chrome, the inputs and the dialogs are NOT resizeable (as designed)

Maybe, at some point, I phase out the zmDialog (and all that) and use something else. Is the input field outside the dialog by default? That should not happen.

**Comment by ba1020** [comment]
the input fields stay inside the Dialog box - and i have to scroll like hell 

i have a 32" screen 4k

**Comment by barrydegraaff** [comment]
Screenshot please

**Comment by barrydegraaff** [comment]
Also you can use the encrypt button that sits in the compose mail window, that way, you do not need to compose from the dialog.

**Comment by ba1020** [comment]
that;s what i do 

![screen](https://cloud.githubusercontent.com/assets/856500/11766892/3e4763ec-a192-11e5-8347-b660bfd39ab4.png)

**Comment by barrydegraaff** [comment]
The idea is that you write your mail in the compose window (then there should be minimal scrolling).

The `message` textarea is in the dialog for backward compatibility (some people prefer to use the zimlet menu OpenPGP -> Encrypt and not the compose window).

Also, if for some reason the compose window integration breaks in future versions of Zimbra, we can fall back to the small `message` textarea.

So the dialog, is not optimal for all use cases. Hope you understand.
So if you werit
