### ISSUE TITLE
Feature request: automic sign.

### ISSUE THREAD

**Issue by tomalbers** [Zimbra-Community/pgp-zimlet#223]
Would it be possible to automatically sign all messages sent to people for which the public key is known in Zimbra (in the list of keys or in the addressbook) ?

**Comment by barrydegraaff** [comment]
Sure, but it is not on the roadmap for now (lack of time and funding)

**Comment by tomalbers** [comment]
Can't fix the lack of time, but if you need funding, ask us, we funded you before for owncloud zimlet.

**Comment by barrydegraaff** [comment]
To be honest, this Zimlet works, but it needs a complete rewrite I estimate that would take me 3 weeks. And around EUR 1000 to complete.

You have to keep in mind that when I started this, there was no emailjs and also OpenPGP.js changed a
lot since the early days.

A lot of bugs I ran into in Zimbra and OpenPGP.js have been fixed in the mean time. But initially this Zimlet did what it could within the possibilities.

So it was nice for the guys over at iway in vietnam, they could start from scratch and take all the good parts. However they do not encrypt drafts and use a lot of heavy frameworks. So far a number of users tried the vietnam version, but did not like it. So I am still maintaining this one here.

Anyway, adding new features is a bit limited with this code-base.

**Comment by tomalbers** [comment]
Barry, 

Allright. If that would involve: 

- storing the keys with the contact (similar to the new smime method, with a seperate filed with the contact) and no longer in the zimlet / contact. 
- Automatic signing as soon as a key is known for all recipients 
- Another go at removing the header/footer (if not possible, then fine) 

We would be willing to donate 250 - 500 euro. Also as gratitude for all your work. So maybe you can find another company to chip in... 

Best, 

Tom Albers 
KovoKs B.V.

**Comment by barrydegraaff** [comment]
For 500 euro, I can implement the requested options, (but not do a full rewrite, its ok I guess)
- storing the keys with the contact (similar to the new smime method, with a seperate filed with the contact) and no longer in the zimlet / contact. 

Disabling Public Key 2-30 in the preferences, are you OK if I make that an optional
feature. So people that are used to it can continue to use it like that.

After you make your donation, I will release within one month. 

you can make donations via:

PayPal: info@barrydegraaff.tk
Bank transfer: IBAN NL55ABNA0623226413 ; BIC ABNANL2A


Kind regards, 

Barry de Graaff
Zeta Alliance 
Co-founder & Developer
zetalliance.org | github.com/Zimbra-Community

+31 617 220 227 | skype: barrydegraaff.tk
Fingerprint: 97f4694a1d9aedad012533db725ddd156d36a2d0

**Comment by tomalbers** [comment]
Hi Barry, 

Just keep it in mind that our offer stands for the rewrite. Maybe you have another customer which can also pay some bits. I don't feel like investing in something that should be rewritten (according to your own words). 

Thanks. 

Tom 

----- Op 9 mei 2018 om 11:39 schreef Barry de Graaff <notifications@github.com>:
