### ISSUE TITLE
Support a global (admin-managed) public key store

### ISSUE THREAD

**Issue by voretaq7** [Zimbra-Community/pgp-zimlet#52]
For some organizations it may be desirable to have a global list of public keys available to every user (for example, a "corporate keychain" containing all the known users in a company and their current/verified keys).

There are some hints as to how this may be possible using Zimlet Configuration templates (config_template.xml) & the getConfigProperty() method as described here: http://wiki.zimbra.com/wiki/Zimlet_Configuration_File

(I've tried this briefly but only succeeded in breaking the zimlet - Opening this issue in case someone else feels motivated before I get around to looking at this again.)

**Comment by barrydegraaff** [comment]
See also:
http://www.zimbra.com/docs/os/6.0.8/administration_guide/Zimlets.11.4.html
zmzimletctl configure config_template.xml 

Or one can implement a keyserver look-up in the Zimlet and the admin installs a keyserver somewhere.

**Comment by tuanta** [comment]
@barrydegraaff is it possible to look up to a GPG public server where most people upload their public keys onto?
E.g. here is my public key: http://keys.fedoraproject.org/pks/lookup?search=0xEF8D50BF&op=vindex

**Comment by barrydegraaff** [comment]
Well I do not trust third parties, so that is why this has not been implemented.
Some research has been done on a server side solution:https://github.com/barrydegraaff/pgp-zimlet/blob/6fdc7e8036d357fe14c3f32f3c6cb7e165dae7cc/test/lookup.jsp
The only good way of exchanging keys is doing it personally, but I agree it would be niceto do look-ups to a company designated key-server.
Barry
Date: Tue, 6 Jan 2015 07:33:14 -0800

**Comment by barrydegraaff** [comment]
The dirty way of setting 128K of (the same) data for each user would be using zmprov like:
zmprov ma user1 +zimbraZimletUserProperties "com_company_testing:favoriteColor:blue"

Also change:
nano /opt/zimbra/conf/attrs/zimbra-attrs.xml
Find the line:
name="zimbraZimletUserProperties" type="cstring" max="5120"
and change it to
name="zimbraZimletUserProperties" type="cstring" max="15120"

Then make on of the users pubkeys read-only for the user.

All the above is NOT a good idea, also with the amount of keys you are talking about
the zimlet should be re-written to handle public keys more targeted. Right now
it just trows together all 40 and iterate trough them... this will become too slow
for what you are doing. So if will have to do a lookup based on for example
the email-address. Avoiding using keys that are not necessary.

Maybe you can use the GAL?

Otherwise the keyserver lookup may be the best way to g.

**Comment by tuanta** [comment]
If you would not like to use a public key server, we can use a private one deployed inside the organization. Other choices are GAL (org level) and personal address book (personal level).

**Comment by voretaq7** [comment]
Speed is actually pretty quick in my testing (128k of keys is about 15 people - just exported as one keyblock instead of multiple. The JS library handles this pretty well.) 

I might give the solution above cramming the property into LDAP (with an appropriately huge length limit & not exposing it to the users) a go Friday -- It's a little annoying, but If that works we can maintain it as a local patch (or I could bang together a pull request and some documentation/scripts using zmprov "gaa" and "ma").

**Comment by barrydegraaff** [comment]
Just add a read only property and then your pull request is more then welcome!!

--- Original Message ---

**Comment by barrydegraaff** [comment]
Combining key blocks also improves speed of LDAP read, since this is one request instead of 15... That saves 10 seconds easy.

--- Original Message ---

**Comment by barrydegraaff** [comment]
An even better solution may be putting a text file in /opt/Zimbra...zimlets-deployed

And read that from the zimlet

--- Original Message ---

**Comment by barrydegraaff** [comment]
Keyserver support has been added in 2.2.6
https://github.com/Zimbra-Community/pgp-zimlet#keyserver-lookup

**Comment by barrydegraaff** [comment]
@voretaq7 can you provide any scripts solutions you may have regarding the combining of public keys?

 (128k of keys is about 15 people - just exported as one keyblock instead of multiple. The JS library handles this pretty well.)

I would like to add some of that to the main code as well. Thanks Barry

**Comment by barrydegraaff** [comment]
And admin-managed global keystore is added, it will be in the 2.5.3 release:
https://github.com/Zimbra-Community/pgp-zimlet/wiki/Global-Keystore
